import { Resend } from 'resend';
import type { InvoiceDetail } from './queries';
import { renderInvoicePdf, renderReceiptPdf } from './pdf/render';
import { formatMoney, formatDate } from './format';
import { docLabel, docLegalLine, isRequestForPayment, totalLabel } from '@claude-invoicer/core';
import type { Invoice, InvoiceLine } from './db/schema';

function escapeHtml(s: string): string {
  const map: Record<string, string> = { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' };
  return s.replace(/[&<>"']/g, (c) => map[c] ?? c);
}

function client(): Resend {
  const key = process.env.RESEND_API_KEY;
  if (!key) throw new Error('RESEND_API_KEY is not set');
  return new Resend(key);
}
function baseUrl(): string {
  return (process.env.APP_BASE_URL || 'https://claude-invoicer-web.vercel.app').replace(/\/$/, '');
}
function fromAddress(): string {
  return process.env.EMAIL_FROM || 'onboarding@resend.dev';
}

function shell(title: string, bodyRows: string): string {
  return `<div style="font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#1a2233;max-width:560px;margin:0 auto;padding:24px">
${title}${bodyRows}
<p style="color:#7a8699;font-size:12px;margin-top:28px">Generated by Claude Invoicer</p>
</div>`;
}

function invoiceHtml(invoice: Invoice, lines: InvoiceLine[], link: string, tz: string): string {
  const docType = invoice.docType;
  const requestsPayment = isRequestForPayment(docType);
  const label = docLabel(docType);
  const legalLine = docLegalLine(docType);
  const rows = lines
    .map(
      (l) =>
        `<tr><td style="padding:6px 0;border-bottom:1px solid #e8ecf3">${escapeHtml(l.label)}</td>
         <td style="padding:6px 0;border-bottom:1px solid #e8ecf3;text-align:right">${formatMoney(l.amount, invoice.currency)}</td></tr>`,
    )
    .join('');
  const intro = !requestsPayment
    ? `Here's your quote <strong>${escapeHtml(invoice.number)}</strong>${invoice.notes ? ` (${escapeHtml(invoice.notes)})` : ''} from ${escapeHtml(invoice.businessName || 'your contractor')}. Reply to this email if you'd like to accept it.`
    : `Here is ${escapeHtml(label.toLowerCase())} <strong>${escapeHtml(invoice.number)}</strong>${invoice.notes ? ` (${escapeHtml(invoice.notes)})` : ''} from ${escapeHtml(invoice.businessName || 'your contractor')}.`;
  const cta = !requestsPayment ? 'View quote' : `View &amp; pay ${escapeHtml(label.toLowerCase())}`;
  const body = `
<p>Hi ${escapeHtml(invoice.clientName || 'there')},</p>
<p>${intro}</p>
<table style="width:100%;border-collapse:collapse;font-size:14px;margin:16px 0">${rows}
<tr><td style="padding:10px 0;font-weight:600">${escapeHtml(totalLabel(docType))}</td>
<td style="padding:10px 0;text-align:right;font-weight:600">${formatMoney(invoice.total, invoice.currency)}</td></tr></table>
${legalLine ? `<p style="color:#7a8699;font-size:12px">${escapeHtml(legalLine)}</p>` : ''}
<p style="margin:24px 0">
  <a href="${link}" style="background:#2563eb;color:#fff;text-decoration:none;padding:12px 20px;border-radius:8px;display:inline-block">${cta}</a>
</p>
<p style="color:#7a8699;font-size:13px">Issued ${formatDate(invoice.issuedAt, tz)}. The full ${escapeHtml(label.toLowerCase())} PDF is attached.</p>`;
  return shell(`<h2 style="margin:0 0 8px">${escapeHtml(label)} ${escapeHtml(invoice.number)}</h2>`, body);
}

function receiptHtml(invoice: Invoice, receiptNumber: string | null, tz: string): string {
  const body = `
<p>Hi ${escapeHtml(invoice.clientName || 'there')},</p>
<p>Thanks — we've recorded invoice <strong>${escapeHtml(invoice.number)}</strong> as paid${invoice.paidAt ? ` on ${formatDate(invoice.paidAt, tz)}` : ''}.</p>
<p>Your receipt${receiptNumber ? ` <strong>${escapeHtml(receiptNumber)}</strong>` : ''} for ${formatMoney(invoice.total, invoice.currency)} is attached.</p>`;
  return shell(`<h2 style="margin:0 0 8px">Receipt ${receiptNumber ? escapeHtml(receiptNumber) : ''}</h2>`, body);
}

export async function sendInvoiceEmail(detail: InvoiceDetail, to: string): Promise<void> {
  const { invoice, lines, settings } = detail;
  const link = `${baseUrl()}/i/${invoice.publicToken}`;
  const pdf = await renderInvoicePdf(detail);
  const { error } = await client().emails.send({
    from: fromAddress(),
    to,
    subject: `${docLabel(invoice.docType)} ${invoice.number} from ${invoice.businessName || 'your contractor'}`,
    html: invoiceHtml(invoice, lines, link, settings.timezone),
    attachments: [{ filename: `${invoice.number}.pdf`, content: Buffer.from(pdf) }],
  });
  if (error) throw new Error(`Resend send failed: ${error.message ?? 'unknown error'}`);
}

export async function sendReceiptEmail(detail: InvoiceDetail, to: string): Promise<void> {
  const { invoice, receiptNumber, settings } = detail;
  const pdf = await renderReceiptPdf(detail);
  const { error } = await client().emails.send({
    from: fromAddress(),
    to,
    subject: `Receipt for invoice ${invoice.number}`,
    html: receiptHtml(invoice, receiptNumber, settings.timezone),
    attachments: [{ filename: `${receiptNumber ?? invoice.number}-receipt.pdf`, content: Buffer.from(pdf) }],
  });
  if (error) throw new Error(`Resend send failed: ${error.message ?? 'unknown error'}`);
}
