export type { SessionEvent, ActivityInterval, FolderMapping } from './types.js';
export { computeIntervals, type TimeEngineOptions } from './time-engine.js';
export {
  normalizePath,
  isUnder,
  matchClientId,
  matchMapping,
  basename,
} from './matcher.js';
export {
  MS_PER_HOUR,
  MS_PER_MIN,
  round2,
  roundMinutesUp,
  activeWithin,
  activeAfter,
  weekStartKey,
  zonedDateToMs,
  weekRange,
  aggregateIntervals,
  buildInvoiceLines,
  invoiceSubtotal,
  adjustmentLine,
  applyFolderCutoffs,
  intervalsForClient,
  unassignedFolders,
  weekProjectDayGrid,
  type ClientAggregate,
  type GroupBy,
  type InvoiceLineInput,
  type InvoiceLine,
  type UnassignedFolder,
  type WeekGridColumn,
  type WeekGridRow,
  type WeekProjectDayGrid,
} from './billing.js';
