<#
.SYNOPSIS
  Installs the Claude Invoicer agent as a hidden Startup-folder launcher that
  auto-starts at logon. Requires NO administrator rights (unlike the Scheduled
  Task installer). Tracking survives PC restarts.

.EXAMPLE
  # Write config + install the launcher:
  .\install-startup.ps1 -ApiUrl "https://your-app.vercel.app" -Token "your-shared-secret"

.EXAMPLE
  # Install the launcher only (config already at ~/.claude-invoicer/agent.json):
  .\install-startup.ps1
#>
[CmdletBinding()]
param(
  [string]$ApiUrl,
  [string]$Token,
  [int]$IdleCapMin = 5,
  [int]$ScanIntervalMin = 5
)

$ErrorActionPreference = "Stop"

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = (Resolve-Path (Join-Path $scriptDir "..\..\..")).Path
$entry = Join-Path $repoRoot "apps\agent\src\index.ts"

$node = (Get-Command node -ErrorAction SilentlyContinue).Source
if (-not $node) { throw "node not found on PATH. Install Node.js >= 20 first." }
if (-not (Test-Path $entry)) { throw "Agent entry not found at $entry" }

# Optionally write the agent config (holds the shared secret).
$cfgDir = Join-Path $env:USERPROFILE ".claude-invoicer"
$cfgPath = Join-Path $cfgDir "agent.json"
if ($ApiUrl -and $Token) {
  if (-not (Test-Path $cfgDir)) { New-Item -ItemType Directory -Path $cfgDir | Out-Null }
  $cfg = [ordered]@{
    apiBaseUrl      = $ApiUrl.TrimEnd('/')
    deviceToken     = $Token
    idleCapMin      = $IdleCapMin
    scanIntervalMin = $ScanIntervalMin
  }
  ($cfg | ConvertTo-Json) | Set-Content -Path $cfgPath -Encoding utf8
  Write-Host "Wrote config to $cfgPath"
}
elseif (-not (Test-Path $cfgPath)) {
  Write-Warning "No agent.json at $cfgPath and no -ApiUrl/-Token supplied. The agent cannot upload until you create it (see SETUP.md)."
}

# Ensure dependencies are installed at the repo root.
if (-not (Test-Path (Join-Path $repoRoot "node_modules\tsx"))) {
  Write-Host "Installing dependencies (npm install)..."
  Push-Location $repoRoot
  try { & npm install | Out-Null } finally { Pop-Location }
}

# A VBScript launcher runs the agent with a fully hidden window (window style 0).
$startup = [Environment]::GetFolderPath('Startup')
$vbsPath = Join-Path $startup "claude-invoicer-agent.vbs"
$cmd = '"' + $node + '" --import tsx "' + $entry + '"'
$vbs = @"
' Auto-generated by install-startup.ps1 - launches the Claude Invoicer agent hidden at logon.
Set sh = CreateObject("WScript.Shell")
sh.CurrentDirectory = "$repoRoot"
sh.Run "$($cmd.Replace('"','""'))", 0, False
"@
Set-Content -Path $vbsPath -Value $vbs -Encoding ascii
Write-Host "Installed startup launcher: $vbsPath"

# Launch it now for this session too.
& wscript.exe $vbsPath
Write-Host "Agent launched (hidden). It scans every $ScanIntervalMin min and relaunches at every logon."
Write-Host "Stop it now with:  Get-Process node | Where-Object { `$_.Path -like '*nodejs*' } | Stop-Process"
Write-Host "Uninstall autostart with:  .\uninstall-startup.ps1"
